### ISSUE TITLE
[4.0] fzaninotto/faker is deprecated and cannot support PHP 8.x

### ISSUE THREAD

**Issue by peter279k** [bowphp/framework#107]
- Version: latest 4.0 branch
- Tintin Version: #.#.#
- PHP Version: 8.x
- Database Driver & Version: N/A

### Description:

- As title, when using the `PHP 8.x` version to run the `composer update --prefer-dist` command, it cannot install the `fzaninotto/faker` package.

### Steps To Reproduce:

- Prepare the `PHP 8.x` version and install the `composer` command.
- Cloning the `framework` repository.
- Using the `cd framework/` to change the directory.
- Running the `php ~/composer.phar update --prefer-dist` command to install the required PHP dependencies.
- The error will happen and error message is as follows:

```sh
peterli@peterli-Virtual-Machine:~/framework$ php ~/composer.phar update --prefer-dist
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires fzaninotto/faker ^1.8 -> satisfiable by fzaninotto/faker[v1.8.0, v1.9.0, v1.9.1, v1.9.2].
```

- I also found that the [fzaninotto/faker](https://github.com/fzaninotto/Faker) package is archived/abandoned now, and I think we should consider find another fake generator library for PHP. It can support `PHP 8.x` versions.

**Comment by papac** [comment]
Fixes by [https://github.com/bowphp/framework/tree/4.4.1](https://github.com/bowphp/framework/tree/4.4.1)
