### ISSUE TITLE
Fix 'Namespace resolution'

### ISSUE THREAD

**Issue by papac** [bowphp/framework#30]

**Comment by houssenedao** [comment]
Hi,
C'est quoi le soucis avec le `Namespace` je peux avoir une description détaillé de l'erreur?

**Comment by papac** [comment]
Hello,
En fait lors de la création de l'api docs avec SAMI de symfony. Il y avait des classes qui n'avaient pas de namespace surtout dans le dossier des Exception/. Je crois que c'est ok pour cet issues.

Désolé j'ai fait le commit sans mettre d'id d'issue.
