### ISSUE TITLE
Manque de support pour les relations entre les models

### ISSUE THREAD

**Issue by mrdionjr** [bowphp/framework#41]
- Version: 3.0
- Database Driver & Version: Mysql

### Description:
Il n'y aucun moyen de créer des relations entre les models.

**Comment by papac** [comment]
C'est juste. Actuellement le système de rélation est base sur système de sous éxecution:

```php
class Pet extends Model {
  public function author() {
     return User::find($this->author_id);
  }
}

$pet = Pet::find(1);
echo $pet->author()->name;
```
