### ISSUE TITLE
vipconsult/proftpd has been problematic

### ISSUE THREAD

**Issue by peter279k** [bowphp/framework#51]
- Version: master

### Description:
It's about the Travis CI build.

The `vipconsult/proftp` Docker image has been problematic because it will present `docker: Error response from daemon: invalid mode: /etc/proftpd/ftpd.passwd` when running Docker image as container.

We can look at this [Travis CI build log](https://travis-ci.org/peter279k/framework-1/jobs/540899981) to know detailed situation.

As we can look at log, I remove `-d` from the `docker run --net=host --name proftpd -v $(pwd)/:/home/$FTP_USER vipconsult/proftpd` command.

It will present `chown: cannot access '/etc/proftpd/ftpd.passwd': No such file or directory` message.

### Suggested solution
- I think we can use other `FTP server` Docker images instead.

@papac, do you have any idea about other Docker images about `FTP server`?

**Comment by peter279k** [comment]
Maybe we can consider this [panubo/vsftpd](https://hub.docker.com/r/panubo/vsftpd) Docker image.

**Comment by mrdionjr** [comment]
@peter279k Thanks peter for pointing this out. I have not experienced with any  ftp server images yet. But I  will take a look.

**Comment by peter279k** [comment]
Closed via PR #52.
