### ISSUE TITLE
Consider removing master branch only in Travis CI build

### ISSUE THREAD

**Issue by peter279k** [bowphp/framework#53]
### Description:
@papac , this is about Travis CI build on specific branches.

I think it doesn't make sense to let this repository run Travis CI build only on `master` branch.

We should make sure repository on active branch should be worked/passed in Travis CI build successfully.

My suggested solutions are as follows:

- Remove `master` branch only definition in Travis CI build. Make all current branches running CI build.
- Keep `mater` branch only existed and add other branches with regular expression in `.travis.yml` setting.

I prefer first solution because it can make sure all oncoming branches (including branches are from PRs)
can be passed/worked in Travis CI build.

### References
- https://docs.travis-ci.com/user/customizing-the-build#using-regular-expressions

**Comment by papac** [comment]
Ok @peter279k. I understand perfectly.

**Comment by papac** [comment]
Thank You @peter279k. I slave the problem.
