### ISSUE TITLE
[4.0] Enhance Bow\Security\Hash class

### ISSUE THREAD

**Issue by peter279k** [bowphp/framework#55]
### Description:

@papac, this is about enhancing `Hash` class.

I've notice that the `Hash` class uses the `PASSWORD_BCRYPT` const directly.

It's not friendly because developers cannot choose their desired password hash algorithms.

My suggestions are as follows:

- Using the configuration to set the current password hash algorithms.
And setting the `PASSWORD_BCRYPT` constraint value by default.
- Adding the constructor in `Hash` class to let developers set current setting before using the `Hash` class to do password hash work.

**Comment by mrdionjr** [comment]
@peter279k That's a good idea, I'll take a look at it this weekend.
