### ISSUE TITLE
[4.0] Enhance Bow\Security\Crypto class

### ISSUE THREAD

**Issue by peter279k** [bowphp/framework#56]
### Description:

@papac . This is about `Enhance Bow\Security\Crypto` class enhancement.

I've found that this class uses `openssl` to do encryption and decryption works.

It's not good because the `sodium` is available since the `php-7.x` versions are released.

I recommend we should change the `openssl` encryption/decryption to `sodium`.

It would be better than `openssl` because of modern Cryptography security :).

### References
- https://www.php.net/manual/en/book.sodium.php
- https://www.futurehosting.com/blog/php-7-2-to-integrate-libsodium-a-powerful-modern-cryptographic-library/
- https://blog.zend.com/2018/11/06/modern-cryptography-in-php-7-2-with-sodium/#.XQHrbo9-WuU

**Comment by papac** [comment]
@peter279k `sodium` is only for `php 7 >= PHP7.2`. You have a other method for solve the problem
